/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamController */

#ifndef _Included_com_threerings_froth_SteamController
#define _Included_com_threerings_froth_SteamController
#ifdef __cplusplus
extern "C" {
#endif
#undef com_threerings_froth_SteamController_MAX_STEAM_CONTROLLERS
#define com_threerings_froth_SteamController_MAX_STEAM_CONTROLLERS 16L
#undef com_threerings_froth_SteamController_RIGHT_TRIGGER_MASK
#define com_threerings_froth_SteamController_RIGHT_TRIGGER_MASK 1LL
#undef com_threerings_froth_SteamController_LEFT_TRIGGER_MASK
#define com_threerings_froth_SteamController_LEFT_TRIGGER_MASK 2LL
#undef com_threerings_froth_SteamController_RIGHT_BUMPER_MASK
#define com_threerings_froth_SteamController_RIGHT_BUMPER_MASK 4LL
#undef com_threerings_froth_SteamController_LEFT_BUMPER_MASK
#define com_threerings_froth_SteamController_LEFT_BUMPER_MASK 8LL
#undef com_threerings_froth_SteamController_BUTTON_0_MASK
#define com_threerings_froth_SteamController_BUTTON_0_MASK 16LL
#undef com_threerings_froth_SteamController_BUTTON_1_MASK
#define com_threerings_froth_SteamController_BUTTON_1_MASK 32LL
#undef com_threerings_froth_SteamController_BUTTON_2_MASK
#define com_threerings_froth_SteamController_BUTTON_2_MASK 64LL
#undef com_threerings_froth_SteamController_BUTTON_3_MASK
#define com_threerings_froth_SteamController_BUTTON_3_MASK 128LL
#undef com_threerings_froth_SteamController_TOUCH_0_MASK
#define com_threerings_froth_SteamController_TOUCH_0_MASK 256LL
#undef com_threerings_froth_SteamController_TOUCH_1_MASK
#define com_threerings_froth_SteamController_TOUCH_1_MASK 512LL
#undef com_threerings_froth_SteamController_TOUCH_2_MASK
#define com_threerings_froth_SteamController_TOUCH_2_MASK 1024LL
#undef com_threerings_froth_SteamController_TOUCH_3_MASK
#define com_threerings_froth_SteamController_TOUCH_3_MASK 2048LL
#undef com_threerings_froth_SteamController_BUTTON_MENU_MASK
#define com_threerings_froth_SteamController_BUTTON_MENU_MASK 4096LL
#undef com_threerings_froth_SteamController_BUTTON_STEAM_MASK
#define com_threerings_froth_SteamController_BUTTON_STEAM_MASK 8192LL
#undef com_threerings_froth_SteamController_BUTTON_ESCAPE_MASK
#define com_threerings_froth_SteamController_BUTTON_ESCAPE_MASK 16384LL
#undef com_threerings_froth_SteamController_BUTTON_BACK_LEFT_MASK
#define com_threerings_froth_SteamController_BUTTON_BACK_LEFT_MASK 32768LL
#undef com_threerings_froth_SteamController_BUTTON_BACK_RIGHT_MASK
#define com_threerings_froth_SteamController_BUTTON_BACK_RIGHT_MASK 65536LL
#undef com_threerings_froth_SteamController_BUTTON_LEFTPAD_CLICKED_MASK
#define com_threerings_froth_SteamController_BUTTON_LEFTPAD_CLICKED_MASK 131072LL
#undef com_threerings_froth_SteamController_BUTTON_RIGHTPAD_CLICKED_MASK
#define com_threerings_froth_SteamController_BUTTON_RIGHTPAD_CLICKED_MASK 262144LL
#undef com_threerings_froth_SteamController_LEFTPAD_FINGERDOWN_MASK
#define com_threerings_froth_SteamController_LEFTPAD_FINGERDOWN_MASK 524288LL
#undef com_threerings_froth_SteamController_RIGHTPAD_FINGERDOWN_MASK
#define com_threerings_froth_SteamController_RIGHTPAD_FINGERDOWN_MASK 1048576LL
/*
 * Class:     com_threerings_froth_SteamController
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamController_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamController_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    getControllerState
 * Signature: (ILcom/threerings/froth/SteamController$State;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamController_getControllerState
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    setOverrideMode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamController_setOverrideMode
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    nativeTriggerHapticPulse
 * Signature: (IIS)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamController_nativeTriggerHapticPulse
  (JNIEnv *, jclass, jint, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
