/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamGameServer */

#ifndef _Included_com_threerings_froth_SteamGameServer
#define _Included_com_threerings_froth_SteamGameServer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _initialized */
/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamGameServer_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    runCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamGameServer_runCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    getSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamGameServer_getSteamID
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    sendUserConnectAndAuthenticate
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/LongBuffer;Lcom/threerings/froth/SteamGameServer$AuthenticateCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamGameServer_sendUserConnectAndAuthenticate
  (JNIEnv *, jclass, jint, jobject, jobject, jobject);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    sendUserDisconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamGameServer_sendUserDisconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    beginAuthSession
 * Signature: (Ljava/nio/ByteBuffer;JLcom/threerings/froth/SteamGameServer$AuthSessionCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamGameServer_beginAuthSession
  (JNIEnv *, jclass, jobject, jlong, jobject);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    endAuthSession
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamGameServer_endAuthSession
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    nativeInit
 * Signature: (ISSSSILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamGameServer_nativeInit
  (JNIEnv *, jclass, jint, jshort, jshort, jshort, jshort, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
