/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamAPI */

#ifndef _Included_com_threerings_froth_SteamAPI
#define _Included_com_threerings_froth_SteamAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamAPI
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamAPI_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamAPI
 * Method:    runCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamAPI_runCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamAPI
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamAPI_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamAPI
 * Method:    nativeIsSteamRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamAPI_nativeIsSteamRunning
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
