/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamInput */

#ifndef _Included_com_threerings_froth_SteamInput
#define _Included_com_threerings_froth_SteamInput
#ifdef __cplusplus
extern "C" {
#endif
#undef com_threerings_froth_SteamInput_MAX_COUNT
#define com_threerings_froth_SteamInput_MAX_COUNT 16L
#undef com_threerings_froth_SteamInput_MAX_ACTIVE_LAYERS
#define com_threerings_froth_SteamInput_MAX_ACTIVE_LAYERS 16L
#undef com_threerings_froth_SteamInput_MAX_ORIGINS
#define com_threerings_froth_SteamInput_MAX_ORIGINS 8L
#undef com_threerings_froth_SteamInput_HANDLE_ALL_CONTROLLERS
#define com_threerings_froth_SteamInput_HANDLE_ALL_CONTROLLERS -1LL
/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nInit
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nInit
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nShutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nShutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nSetInputActionManifestFilePath
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nSetInputActionManifestFilePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nRunFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nRunFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nBWaitForData
 * Signature: (ZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nBWaitForData
  (JNIEnv *, jclass, jboolean, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nBNewDataAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nBNewDataAvailable
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetConnectedControllers
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetConnectedControllers
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nEnableDeviceCallbacks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nEnableDeviceCallbacks
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetActionSetHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamInput_nGetActionSetHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nActivateActionSet
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nActivateActionSet
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetCurrentActionSet
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamInput_nGetCurrentActionSet
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nActivateActionSetLayer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nActivateActionSetLayer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nDeactivateActionSetLayer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nDeactivateActionSetLayer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nDeactivateAllActionSetLayers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nDeactivateAllActionSetLayers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetActiveActionSetLayers
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetActiveActionSetLayers
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetDigitalActionHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamInput_nGetDigitalActionHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetDigitalActionData
 * Signature: (JJLcom/threerings/froth/SteamInput/DigitalActionData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nGetDigitalActionData
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetDigitalActionOrigins
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetDigitalActionOrigins
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetStringForDigitalActionName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetStringForDigitalActionName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetAnalogActionHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamInput_nGetAnalogActionHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetAnalogActionData
 * Signature: (JJLcom/threerings/froth/SteamInput/AnalogActionData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nGetAnalogActionData
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetAnalogActionOrigins
 * Signature: (JJJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetAnalogActionOrigins
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetStringForAnalogActionName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetStringForAnalogActionName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nStopAnalogActionMomentum
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nStopAnalogActionMomentum
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetMotionData
 * Signature: (JLcom/threerings/froth/SteamInput/MotionData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nGetMotionData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetGlyphPNGForActionOrigin
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetGlyphPNGForActionOrigin
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetGlyphSVGForActionOrigin
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetGlyphSVGForActionOrigin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetGlyphForActionOriginLegacy
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetGlyphForActionOriginLegacy
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetStringForActionOrigin
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetStringForActionOrigin
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetStringForXboxOrigin
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetStringForXboxOrigin
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetGlyphForXboxOrigin
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamInput_nGetGlyphForXboxOrigin
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetActionOriginFromXboxOrigin
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetActionOriginFromXboxOrigin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nTranslateActionOrigin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nTranslateActionOrigin
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nTriggerVibration
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nTriggerVibration
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nTriggerVibrationExtended
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nTriggerVibrationExtended
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nTriggerSimpleHapticEvent
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nTriggerSimpleHapticEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nSetLEDColor
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nSetLEDColor
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nLegacyTriggerHapticPulse
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nLegacyTriggerHapticPulse
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nLegacyTriggerRepeatedHapticPulse
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamInput_nLegacyTriggerRepeatedHapticPulse
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nShowBindingPanel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nShowBindingPanel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetInputTypeForHandle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetInputTypeForHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetControllerForGamepadIndex
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamInput_nGetControllerForGamepadIndex
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetGamepadIndexForController
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetGamepadIndexForController
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetDeviceBindingRevision
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamInput_nGetDeviceBindingRevision
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetRemotePlaySessionID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetRemotePlaySessionID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamInput
 * Method:    nGetSessionInputConfigurationSettings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamInput_nGetSessionInputConfigurationSettings
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
