/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamUser */

#ifndef _Included_com_threerings_froth_SteamUser
#define _Included_com_threerings_froth_SteamUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamUser
 * Method:    getSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamUser_getSteamID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
