/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamUtils */

#ifndef _Included_com_threerings_froth_SteamUtils
#define _Included_com_threerings_froth_SteamUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamUtils
 * Method:    getAppID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamUtils_getAppID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
