/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamGameServerStats */

#ifndef _Included_com_threerings_froth_SteamGameServerStats
#define _Included_com_threerings_froth_SteamGameServerStats
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamGameServerStats
 * Method:    setUserAchievement
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamGameServerStats_setUserAchievement
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_threerings_froth_SteamGameServerStats
 * Method:    clearUserAchievement
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamGameServerStats_clearUserAchievement
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
