/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamFriends */

#ifndef _Included_com_threerings_froth_SteamFriends
#define _Included_com_threerings_froth_SteamFriends
#ifdef __cplusplus
extern "C" {
#endif
#undef com_threerings_froth_SteamFriends_FRIEND_FLAG_IMMEDIATE
#define com_threerings_froth_SteamFriends_FRIEND_FLAG_IMMEDIATE 4L
/* Inaccessible static: _gameRichPresenceJoinRequestCallbacks */
/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    getPersonaName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamFriends_getPersonaName
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    getFriendCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamFriends_getFriendCount
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    getFriendByIndex
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamFriends_getFriendByIndex
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    getFriendPersonaName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamFriends_getFriendPersonaName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    setInGameVoiceSpeaking
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamFriends_setInGameVoiceSpeaking
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    activateGameOverlayToWebPage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamFriends_activateGameOverlayToWebPage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    setRichPresence
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamFriends_setRichPresence
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    getFriendRichPresence
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_threerings_froth_SteamFriends_getFriendRichPresence
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    inviteUserToGame
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamFriends_inviteUserToGame
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    nativeGetFriendPersonaState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamFriends_nativeGetFriendPersonaState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamFriends
 * Method:    addNativeGameRichPresenceJoinRequestCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamFriends_addNativeGameRichPresenceJoinRequestCallback
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
