/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamUser */

#ifndef _Included_com_threerings_froth_SteamUser
#define _Included_com_threerings_froth_SteamUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamUser
 * Method:    getSteamID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_threerings_froth_SteamUser_getSteamID
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamUser
 * Method:    initiateGameConnection
 * Signature: (Ljava/nio/ByteBuffer;JISZ)I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamUser_initiateGameConnection
  (JNIEnv *, jclass, jobject, jlong, jint, jshort, jboolean);

/*
 * Class:     com_threerings_froth_SteamUser
 * Method:    terminateGameConnection
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamUser_terminateGameConnection
  (JNIEnv *, jclass, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
