/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamUtils */

#ifndef _Included_com_threerings_froth_SteamUtils
#define _Included_com_threerings_froth_SteamUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamUtils
 * Method:    getAppID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_threerings_froth_SteamUtils_getAppID
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamUtils
 * Method:    setWarningMessageHook
 * Signature: (Lcom/threerings/froth/SteamUtils/WarningMessageHook;)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamUtils_setWarningMessageHook
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_threerings_froth_SteamUtils
 * Method:    isOverlayEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamUtils_isOverlayEnabled
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamUtils
 * Method:    overlayNeedsPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamUtils_overlayNeedsPresent
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamUtils
 * Method:    nativeSetOverlayNotificationPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamUtils_nativeSetOverlayNotificationPosition
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
