/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamController */

#ifndef _Included_com_threerings_froth_SteamController
#define _Included_com_threerings_froth_SteamController
#ifdef __cplusplus
extern "C" {
#endif
#undef com_threerings_froth_SteamController_MAX_STEAM_CONTROLLERS
#define com_threerings_froth_SteamController_MAX_STEAM_CONTROLLERS 16L
/* Inaccessible static: _initialized */
/*
 * Class:     com_threerings_froth_SteamController
 * Method:    nInit
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamController_nInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    nShutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamController_nShutdown
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    nGetControllerState
 * Signature: (ILcom/threerings/froth/SteamController$State;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamController_nGetControllerState
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    nTriggerHapticPulse
 * Signature: (IIS)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamController_nTriggerHapticPulse
  (JNIEnv *, jclass, jint, jint, jshort);

/*
 * Class:     com_threerings_froth_SteamController
 * Method:    nSetOverrideMode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamController_nSetOverrideMode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
