/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamGameServer */

#ifndef _Included_com_threerings_froth_SteamGameServer
#define _Included_com_threerings_froth_SteamGameServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    sendUserConnectAndAuthenticate
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/LongBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamGameServer_sendUserConnectAndAuthenticate
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     com_threerings_froth_SteamGameServer
 * Method:    sendUserDisconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamGameServer_sendUserDisconnect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
