/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamMatchmaking */

#ifndef _Included_com_threerings_froth_SteamMatchmaking
#define _Included_com_threerings_froth_SteamMatchmaking
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _gameLobbyJoinRequestCallbacks */
/*
 * Class:     com_threerings_froth_SteamMatchmaking
 * Method:    joinLobby
 * Signature: (JLcom/threerings/froth/SteamMatchmaking$EnterLobbyCallback;)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamMatchmaking_joinLobby
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_threerings_froth_SteamMatchmaking
 * Method:    leaveLobby
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamMatchmaking_leaveLobby
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_threerings_froth_SteamMatchmaking
 * Method:    inviteUserToLobby
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamMatchmaking_inviteUserToLobby
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_threerings_froth_SteamMatchmaking
 * Method:    nativeCreateLobby
 * Signature: (IILcom/threerings/froth/SteamMatchmaking$CreateLobbyCallback;)V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamMatchmaking_nativeCreateLobby
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_threerings_froth_SteamMatchmaking
 * Method:    addNativeGameLobbyJoinRequestCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamMatchmaking_addNativeGameLobbyJoinRequestCallback
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
