/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_threerings_froth_SteamAPI */

#ifndef _Included_com_threerings_froth_SteamAPI
#define _Included_com_threerings_froth_SteamAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_threerings_froth_SteamAPI
 * Method:    Init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_threerings_froth_SteamAPI_Init
  (JNIEnv *, jclass);

/*
 * Class:     com_threerings_froth_SteamAPI
 * Method:    Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_threerings_froth_SteamAPI_Shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
